### ISSUE TITLE
Should Notebook outputs cleared check be run on push to branch or only on PR?

### ISSUE THREAD

**Issue by wmwv** [LSSTDESC/DC2-analysis#156]
Should the GitHub Actions check-notebook-outputs script be run on every push to a branch or only on a PR?

**Comment by wmwv** [comment]
My preference would be only on PR, because I don't want to be discouraged from pushing changes.

But I'm happy to yield to popular opinion.

**Comment by wmwv** [comment]
@yymao @JoanneBogart Do you have clear opinions on this?

**Comment by yymao** [comment]
yep, that's fine. I guess it should still run if the commit is pushed to master. We can change the trigger to:

```yaml
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
```
